config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  root 'feeds#index'
  get 'sessions/new'
  resources :users, only: [:new, :create, :show, :index]
  resources :feeds do
    resources :comments
    collection do
      post :confirm
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
    end
  end
  resources :conversations do
  resources :messages
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :feed
  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_feed, only: [:create, :edit, :update]
  # コメントを保存、投稿するためのアクションです。
  def create
    # Blogをパラメータの値から探し出し,Blogに紐づくcommentsとしてbuildします。
    @feed = Feed.find(params[:feed_id])
    @comment = @feed.comments.build(comment_params)
    # クライアント要求に応じてフォーマットを変更
    respond_to do |format|
      if @comment.save
        format.js { render :index }
      else
        format.html { redirect_to feed_path(@feed), notice: '投稿できませんでした...' }
      end
    end
  end

  def edit
    @comment = @feed.comments.find(params[:id])
    respond_to do |format|
      flash.now[:notice] = 'コメントの編集中'
      format.js { render :edit }
    end
  end

  def update
    @comment = @feed.comments.find(params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        flash.now[:notice] = 'コメントが編集されました'
        format.js { render :index }
      else
        flash.now[:notice] = 'コメントの編集に失敗しました'
        format.js { render :edit_error }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      flash.now[:notice] = 'コメントが削除されました'
      format.js { render :index }
    end
  end
  
  private
  # ストロングパラメーター
  def comment_params
    params.require(:comment).permit(:feed_id, :content)
  end

  def set_feed
    @feed = Feed.find(params[:feed_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_edit.html.erb
<%= form_with(model: [feed, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.text_area :content, id: "comment_content_#{feed.id}" %>
    <%= form.label :content %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<!-- この記述がblogのshow画面に表示されるコメント入力欄になります -->
<%= form_with(model: [feed, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% if comment.id.present? %>
      <li>
        <div class="comment-content" id ="this_comment_<%= comment.id %>"></div>
        <p><%= comment.content %></p>
        <p><%= link_to "コメント編集", edit_feed_comment_path(feed, comment), remote: true %></p>
        <p><%= link_to "コメント削除", feed_comment_path(comment.feed_id, comment.id), method: :delete, remote: true,
                                data: { confirm: "本当に削除しますか?"} %></p>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/edit.js.erb
$("#this_comment_<%= @comment.id %>").replaceWith("<%= j render 'comments/edit', feed: @feed, comment: @comment %>");
$("#notice").html("<%= j flash[:notice] %>");

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.feed.comments, feed: @comment.feed }) %>");
$("textarea").val('');
$("#notice").html("<%= j flash[:notice] %>");