faceblog/config/routes.rb
Rails.application.routes.draw do
  root 'feeds#index'
  get 'sessions/new'
  resources :users, only: [:new, :create, :show]
  resources :feeds do
    collection do
      post :confirm
  resources :sessions, only: [:new, :create, :destroy]
    end
  end
end

faceblog/app/models/feed.rb
class Feed < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user, optional: true
  validates :content, presence: true
  validates :image, presence: true
end

faceblog/app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
             format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :feeds
end

faceblog/app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  protect_from_forgery
  before_action :set_feed, only: %i[show edit update destroy ]
  before_action :authenticate_user, {only: [:create, :confirm]}
  def index
    @feeds = Feed.all
    @users = User.all
  end
  def show
  end

  def new
    if params[:back]
      @feed = Feed.new(feed_params)
    else
      @feed = Feed.new
    end
  end

  def create
    @feed = current_user.feeds.build(feed_params)
    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: "Feed was successfully created." }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def confirm
    @feed = current_user.feeds.build(feed_params)
  end

  def edit
  end

  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: "Feed was successfully updated." }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: "Feed was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def login?
  # 既ログインならばtrue、未ログインならばfalseを返す
  end

  private
  def set_feed
    @feed = Feed.find(params[:id])
  end
  def feed_params
    params.require(:feed).permit(:image, :image_cache, :content, :user_id)
    # .merge(user_id: current_user.id)
  end
end

faceblog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end
  def show
    @user = User.find(params[:id])
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

faceblog/app/views/feeds/show.html.erb
<h1>Details</h1>
<p id="notice"><%= notice %></p>
<p>
  <strong>Image:</strong>
  <% if !@feed.image.url.nil? %>
  <%= image_tag @feed.image.url %>
  <% end %>
  <strong>message:</strong>
  <%= @feed.content %>
</p>
<% if @feed.user == current_user %>
  <%= link_to "Edit", edit_feed_path %>
<% else %>
  <a></a>
<% end %>
<%= link_to 'Back', feeds_path %>

faceblog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Faceblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="wrapper">
    <header>
      <%= image_tag "facebook.png", class: "logo_image"%>
      <nav>
        <ul class="top_menu">
          <li><%= link_to 'Home', feeds_path %></li>
          <li>
            <% if logged_in? %>
            <%= link_to "Profile", user_path(current_user.id) %>
          </li>
          <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
          <li>
            <% else %>
            <%= link_to "Sign up", new_user_path %>
          </li>
          <li>
            <%= link_to "Login", new_session_path %>
            <% end %>
          </li>
          <li>
            <% if logged_in? %>
            <%= link_to 'share', new_feed_path %>
            <% end %>
          </li>
        </ul>
      </nav>
    </header>
    <%= yield %>
    <footer>
      <p>プライバシー·利用規約·広告·Ad Choices</p>
      <p>Cookie·その他·Faceblog©2021</p>
    </footer>
    </div>
  </body>
</html>